name: VKube CI/CD

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]



jobs:

  build-and-deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout repository

        uses: actions/checkout@v3



      - name: Setup Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.x'



      - name: Install VKube CLI

        run: pip3 install vkube



      - name: Configure VKube

        run: |

          vkube config set token ${{ secrets.VKUBE_TOKEN }}

          vkube config set registry ${{ secrets.VKUBE_REGISTRY }}



      - name: Deploy with VKube

        run: vkube deploy -f VKubefile.yaml
